//! Bake the voice tree into the binary.
//!
//! The engine image is already `include_bytes!`d into `loqng-eng`. This does
//! the same for the other half — the voice data and the four module files
//! the engine opens before it asks `dlopen` for them — so a deployed binary
//! needs nothing beside it.
//!
//! Where the tree comes from, in order:
//!
//! ```text
//! $LOQ_LIB / $LOQ_DATA    explicit
//! engine/{lib,data}       the repo, which is the default
//! ```
//!
//! If neither is there the crate still builds, with an empty tree, and
//! `loqspeak` falls back to `--lib`/`--data` at run time. That keeps a
//! checkout without the voice data compiling.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-env-changed=LOQ_LIB");
    println!("cargo:rerun-if-env-changed=LOQ_DATA");

    let root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let sibling = root.parent().unwrap().parent().unwrap().join("engine");

    let lib = env::var_os("LOQ_LIB")
        .map(PathBuf::from)
        .unwrap_or_else(|| sibling.join("lib"));
    let data = env::var_os("LOQ_DATA")
        .map(PathBuf::from)
        .unwrap_or_else(|| sibling.join("data"));

    let mut files = Vec::new();
    collect(&lib, "/loq/lib", &mut files);
    collect(&data, "/loq/data", &mut files);
    files.sort();

    let mut out = String::from(
        "// Generated by build.rs -- the voice tree, verbatim.\n\n\
         pub static FILES: &[(&str, &[u8])] = &[\n",
    );
    let mut total = 0u64;
    for (guest, real) in &files {
        total += fs::metadata(real).map(|m| m.len()).unwrap_or(0);
        println!("cargo:rerun-if-changed={}", real.display());
        out.push_str(&format!("    ({:?}, include_bytes!({:?})),\n", guest, real));
    }
    out.push_str("];\n");

    let dst = PathBuf::from(env::var("OUT_DIR").unwrap()).join("voice.rs");
    fs::write(&dst, out).expect("writing voice.rs");
    println!(
        "cargo:warning=loqng-voice: {} files, {:.1} MB built in",
        files.len(),
        total as f64 / (1024.0 * 1024.0)
    );
}

/// Every file under `dir`, as (guest path, real path).
fn collect(dir: &Path, prefix: &str, out: &mut Vec<(String, PathBuf)>) {
    let Ok(rd) = fs::read_dir(dir) else { return };
    println!("cargo:rerun-if-changed={}", dir.display());
    for e in rd.filter_map(|e| e.ok()) {
        let name = e.file_name().to_string_lossy().into_owned();
        let guest = format!("{prefix}/{name}");
        if e.path().is_dir() {
            collect(&e.path(), &guest, out);
        } else {
            out.push((guest, e.path()));
        }
    }
}
