//! Generated by `tools/engxlate.py` -- do not edit.
//!
//! The Loquendo TTS 6 engine: every function of every module,
//! one Rust statement per ARM instruction, with the loaded
//! memory image beside it. See `HANDOFF.md` §4.

mod loqaudiofile_so_0;
mod loqenglish6_9_so_0;
mod loqenglish6_9_so_1;
mod loqenglish6_9_so_2;
mod loqenglish6_9_so_3;
mod loqenglish6_9_so_4;
mod loqmsx_so_0;
mod loqmsx_so_1;
mod loqmsx_so_2;
mod loqtts6_so_0;
mod loqtts6_so_1;
mod loqtts6_so_10;
mod loqtts6_so_11;
mod loqtts6_so_12;
mod loqtts6_so_13;
mod loqtts6_so_14;
mod loqtts6_so_15;
mod loqtts6_so_16;
mod loqtts6_so_17;
mod loqtts6_so_18;
mod loqtts6_so_2;
mod loqtts6_so_3;
mod loqtts6_so_4;
mod loqtts6_so_5;
mod loqtts6_so_6;
mod loqtts6_so_7;
mod loqtts6_so_8;
mod loqtts6_so_9;

pub use loqaudiofile_so_0::*;
pub use loqenglish6_9_so_0::*;
pub use loqenglish6_9_so_1::*;
pub use loqenglish6_9_so_2::*;
pub use loqenglish6_9_so_3::*;
pub use loqenglish6_9_so_4::*;
pub use loqmsx_so_0::*;
pub use loqmsx_so_1::*;
pub use loqmsx_so_2::*;
pub use loqtts6_so_0::*;
pub use loqtts6_so_1::*;
pub use loqtts6_so_10::*;
pub use loqtts6_so_11::*;
pub use loqtts6_so_12::*;
pub use loqtts6_so_13::*;
pub use loqtts6_so_14::*;
pub use loqtts6_so_15::*;
pub use loqtts6_so_16::*;
pub use loqtts6_so_17::*;
pub use loqtts6_so_18::*;
pub use loqtts6_so_2::*;
pub use loqtts6_so_3::*;
pub use loqtts6_so_4::*;
pub use loqtts6_so_5::*;
pub use loqtts6_so_6::*;
pub use loqtts6_so_7::*;
pub use loqtts6_so_8::*;
pub use loqtts6_so_9::*;

mod dispatch;
pub use dispatch::{blocks, call_addr};
mod image;
pub use image::{regions, EXPORTS, HOSTDATA, INIT, MODULES};
