//! Generated by `tools/engxlate.py` -- do not edit.

#![allow(
    clippy::all,
    unused_assignments,
    unused_mut,
    unused_parens,
    unused_braces,
    unreachable_code,
    unused_variables,
    non_snake_case,
    unused_imports
)]

use super::*;
use loqng_xrt::{self as xrt, Cpu, Flags, Host, Mem};

pub fn f_002907f4(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host) {
    f_002907f4_at(c, m, h, 0x2907f4)
}

/// Enter at any of this function's blocks. The engine takes the
/// address of code that is not a function start, so an indirect
/// call has to be able to land mid-function.
pub fn f_002907f4_at(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host, start: u32) {
    let mut pc: u32 = start;
    let mut f = c.f;
    loop {
        #[cfg(feature = "cover")]
        xrt::hit(pc, &c.r);
        match pc {
            0x2907f4 => {
                {
                    let ea = c.r[13].wrapping_sub(0x4);
                    let nb = c.r[13].wrapping_sub(0x4);
                    m.w32(ea, c.r[10]);
                    c.r[13] = nb;
                }
                c.r[10] = 0x8be8_u32;
                c.r[10] = Flags::add(0x290804_u32, c.r[10]).0;
                c.r[12] = 0x6_u32;
                f = Flags::sub(c.r[0], 0x0_u32).1;
                if f.z {
                    pc = 0x290848;
                    continue;
                }
                f = Flags::sub(c.r[1], 0x0_u32).1;
                if !f.z {
                    pc = 0x290848;
                    continue;
                }
                c.r[2] = 0x0_u32;
                f = Flags::sub(c.r[2], c.r[12]).1;
                if f.c {
                    pc = 0x290848;
                    continue;
                }
                c.r[3] = 0xffffff3c_u32;
                c.r[1] = Flags::add(c.r[10], c.r[3]).0;
                pc = 0x290828;
            }
            0x290828 => {
                {
                    let ea = c.r[1].wrapping_add((c.r[2] << 3));
                    c.r[3] = m.r32(ea);
                }
                f = Flags::sub(c.r[0], c.r[3]).1;
                if f.z {
                    c.r[3] = Flags::add(c.r[1], (c.r[2] << 3)).0;
                }
                if f.z {
                    {
                        let ea = c.r[3].wrapping_add(0x4);
                        c.r[0] = m.r32(ea);
                    }
                }
                if f.z {
                    pc = 0x29084c;
                    continue;
                }
                c.r[2] = Flags::add(c.r[2], 0x1_u32).0;
                f = Flags::sub(c.r[2], c.r[12]).1;
                if !f.c {
                    pc = 0x290828;
                    continue;
                }
                pc = 0x290848;
            }
            0x290848 => {
                c.r[0] = 0x0_u32;
                pc = 0x29084c;
            }
            0x29084c => {
                {
                    let b = c.r[13];
                    c.r[10] = m.r32(b.wrapping_add(0x0));
                    c.r[13] = b.wrapping_add(0x4);
                }
                c.f = f;
                return;
            }
            _ => unreachable!("f_002907f4: no block at {pc:#x}"),
        }
    }
}

pub fn f_0029085c(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host) {
    f_0029085c_at(c, m, h, 0x29085c)
}

/// Enter at any of this function's blocks. The engine takes the
/// address of code that is not a function start, so an indirect
/// call has to be able to land mid-function.
pub fn f_0029085c_at(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host, start: u32) {
    let mut pc: u32 = start;
    let mut f = c.f;
    loop {
        #[cfg(feature = "cover")]
        xrt::hit(pc, &c.r);
        match pc {
            0x29085c => {
                {
                    let b = c.r[13];
                    m.w32(b.wrapping_add(0xfffffff8), c.r[10]);
                    m.w32(b.wrapping_add(0xfffffffc), c.r[14]);
                    c.r[13] = b.wrapping_add(0xfffffff8);
                }
                c.r[10] = 0x8b80_u32;
                c.r[10] = Flags::add(0x29086c_u32, c.r[10]).0;
                c.r[3] = 0x40_u32;
                {
                    let ea = c.r[10].wrapping_add(c.r[3]);
                    c.r[1] = m.r32(ea);
                }
                c.r[2] = 0x2_u32;
                c.r[14] = 0x290878;
                c.f = f;
                xrt::memcpy(c, m);
                f = c.f;
                c.r[0] = 0x0_u32;
                {
                    let b = c.r[13];
                    c.r[10] = m.r32(b.wrapping_add(0x0));
                    c.r[13] = b.wrapping_add(0x8);
                    c.f = f;
                    return;
                }
            }
            _ => unreachable!("f_0029085c: no block at {pc:#x}"),
        }
    }
}

pub fn f_00290888(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host) {
    f_00290888_at(c, m, h, 0x290888)
}

/// Enter at any of this function's blocks. The engine takes the
/// address of code that is not a function start, so an indirect
/// call has to be able to land mid-function.
pub fn f_00290888_at(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host, start: u32) {
    let mut pc: u32 = start;
    let mut f = c.f;
    loop {
        #[cfg(feature = "cover")]
        xrt::hit(pc, &c.r);
        match pc {
            0x290888 => {
                {
                    let ea = c.r[13].wrapping_sub(0x4);
                    let nb = c.r[13].wrapping_sub(0x4);
                    m.w32(ea, c.r[14]);
                    c.r[13] = nb;
                }
                c.r[12] = 0x0_u32;
                c.r[2] = c.r[12];
                f = Flags::sub(c.r[0], c.r[12]).1;
                if f.z {
                    c.r[0] = c.r[12];
                }
                if f.z {
                    {
                        let b = c.r[13];
                        c.r[13] = b.wrapping_add(0x4);
                        c.f = f;
                        return;
                    }
                }
                c.r[3] = 0x0_u32;
                {
                    let ea = c.r[0];
                    m.w8(ea, c.r[3] as u8);
                }
                f = Flags::sub(c.r[1], c.r[3]).1;
                if f.z {
                    c.r[0] = c.r[1];
                }
                if f.z {
                    {
                        let b = c.r[13];
                        c.r[13] = b.wrapping_add(0x4);
                        c.f = f;
                        return;
                    }
                }
                {
                    let ea = c.r[1];
                    c.r[3] = m.r8(ea) as u32;
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if f.z {
                    pc = 0x29093c;
                    continue;
                }
                c.r[14] = 0x25_u32;
                pc = 0x2908c4;
            }
            0x2908c4 => {
                {
                    let ea = c.r[1];
                    c.r[3] = m.r8(ea) as u32;
                }
                f = Flags::sub(c.r[3], 0x3f_u32).1;
                if !f.z {
                    f = Flags::sub(c.r[3], 0x25_u32).1;
                }
                if !f.z {
                    pc = 0x2908e8;
                    continue;
                }
                f = Flags::sub(c.r[2], 0x0_u32).1;
                if f.z {
                    c.r[12] = Flags::add(c.r[12], 0x1_u32).0;
                }
                f = Flags::sub(c.r[2], 0x8_u32).1;
                if (!f.c || f.z) {
                    c.r[2] = Flags::add(c.r[2], 0x1_u32).0;
                }
                pc = 0x290930;
                continue;
            }
            0x2908e8 => {
                f = Flags::sub(c.r[12], 0x1_u32).1;
                if !f.z {
                    c.r[3] = 0x0_u32;
                }
                if f.z {
                    c.r[3] = 0x1_u32;
                }
                f = Flags::sub(c.r[2], 0x0_u32).1;
                if f.z {
                    c.r[3] = 0x0_u32;
                }
                if !f.z {
                    c.r[3] = c.r[3] & 0x1_u32;
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if f.z {
                    pc = 0x290924;
                    continue;
                }
                {
                    let ea = c.r[0];
                    let nb = c.r[0].wrapping_add(0x1);
                    m.w8(ea, c.r[14] as u8);
                    c.r[0] = nb;
                }
                c.r[3] = 0x30_u32;
                {
                    let ea = c.r[0];
                    let nb = c.r[0].wrapping_add(0x1);
                    m.w8(ea, c.r[3] as u8);
                    c.r[0] = nb;
                }
                c.r[3] = Flags::add(c.r[2], c.r[3]).0;
                {
                    let ea = c.r[0];
                    let nb = c.r[0].wrapping_add(0x1);
                    m.w8(ea, c.r[3] as u8);
                    c.r[0] = nb;
                }
                c.r[3] = 0x64_u32;
                {
                    let ea = c.r[0];
                    let nb = c.r[0].wrapping_add(0x1);
                    m.w8(ea, c.r[3] as u8);
                    c.r[0] = nb;
                }
                pc = 0x290924;
            }
            0x290924 => {
                {
                    let ea = c.r[1];
                    c.r[3] = m.r8(ea) as u32;
                }
                {
                    let ea = c.r[0];
                    let nb = c.r[0].wrapping_add(0x1);
                    m.w8(ea, c.r[3] as u8);
                    c.r[0] = nb;
                }
                c.r[2] = 0x0_u32;
                pc = 0x290930;
            }
            0x290930 => {
                {
                    let ea = c.r[1].wrapping_add(0x1);
                    let nb = c.r[1].wrapping_add(0x1);
                    c.r[3] = m.r8(ea) as u32;
                    c.r[1] = nb;
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if !f.z {
                    pc = 0x2908c4;
                    continue;
                }
                pc = 0x29093c;
            }
            0x29093c => {
                c.r[3] = 0x0_u32;
                {
                    let ea = c.r[0];
                    m.w8(ea, c.r[3] as u8);
                }
                c.r[0] = c.r[12];
                {
                    let b = c.r[13];
                    c.r[13] = b.wrapping_add(0x4);
                    c.f = f;
                    return;
                }
            }
            _ => unreachable!("f_00290888: no block at {pc:#x}"),
        }
    }
}

pub fn f_0029094c(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host) {
    f_0029094c_at(c, m, h, 0x29094c)
}

/// Enter at any of this function's blocks. The engine takes the
/// address of code that is not a function start, so an indirect
/// call has to be able to land mid-function.
pub fn f_0029094c_at(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host, start: u32) {
    let mut pc: u32 = start;
    let mut f = c.f;
    loop {
        #[cfg(feature = "cover")]
        xrt::hit(pc, &c.r);
        match pc {
            0x29094c => {
                {
                    let b = c.r[13];
                    m.w32(b.wrapping_add(0xffffffe0), c.r[4]);
                    m.w32(b.wrapping_add(0xffffffe4), c.r[5]);
                    m.w32(b.wrapping_add(0xffffffe8), c.r[6]);
                    m.w32(b.wrapping_add(0xffffffec), c.r[7]);
                    m.w32(b.wrapping_add(0xfffffff0), c.r[8]);
                    m.w32(b.wrapping_add(0xfffffff4), c.r[9]);
                    m.w32(b.wrapping_add(0xfffffff8), c.r[10]);
                    m.w32(b.wrapping_add(0xfffffffc), c.r[14]);
                    c.r[13] = b.wrapping_add(0xffffffe0);
                }
                c.r[13] = Flags::sub(c.r[13], 0x200_u32).0;
                c.r[10] = 0x8a8c_u32;
                c.r[10] = Flags::add(0x290960_u32, c.r[10]).0;
                c.r[4] = c.r[0];
                c.r[6] = c.r[1];
                c.r[9] = c.r[2];
                c.r[8] = c.r[3];
                {
                    let ea = c.r[13].wrapping_add(0x220);
                    c.r[3] = m.r32(ea);
                }
                c.r[7] = 0x0_u32;
                f = Flags::sub(c.r[3], c.r[7]).1;
                if !f.z {
                    {
                        let ea = c.r[3];
                        m.w8(ea, c.r[7] as u8);
                    }
                }
                c.r[0] = 0x264_u32;
                c.r[14] = 0x290984;
                c.f = f;
                h.import("malloc", c, m);
                f = c.f;
                c.r[5] = c.r[0];
                {
                    let ea = c.r[4];
                    m.w32(ea, c.r[0]);
                }
                c.r[1] = 0x0_u32;
                c.r[2] = 0x264_u32;
                c.r[14] = 0x290998;
                c.f = f;
                xrt::memset(c, m);
                f = c.f;
                f = Flags::sub(c.r[5], 0x0_u32).1;
                if f.z {
                    c.r[0] = 0x1_u32;
                }
                if f.z {
                    pc = 0x290ab4;
                    continue;
                }
                c.r[3] = 0x1_u32;
                {
                    let ea = c.r[5].wrapping_add(0x4);
                    m.w32(ea, c.r[3]);
                }
                c.r[3] = 0x0_u32;
                {
                    let ea = c.r[5];
                    m.w8(ea, c.r[3] as u8);
                }
                {
                    let ea = c.r[5].wrapping_add(0x21c);
                    m.w32(ea, c.r[3]);
                }
                f = Flags::sub(c.r[6], c.r[3]).1;
                if f.z {
                    pc = 0x2909cc;
                    continue;
                }
                {
                    let ea = c.r[6];
                    c.r[3] = m.r8(ea) as u32;
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if !f.z {
                    pc = 0x2909dc;
                    continue;
                }
                pc = 0x2909cc;
            }
            0x2909cc => {
                c.r[0] = c.r[5];
                c.r[14] = 0x2909d4;
                c.f = f;
                h.import("free", c, m);
                f = c.f;
                c.r[0] = 0x3_u32;
                pc = 0x290ab4;
                continue;
            }
            0x2909dc => {
                c.r[0] = c.r[6];
                c.r[14] = 0x2909e4;
                c.f = f;
                xrt::strlen(c, m);
                f = c.f;
                f = Flags::sub(c.r[0], 0x4_u32).1;
                if (!f.c || f.z) {
                    pc = 0x290a08;
                    continue;
                }
                c.r[0] = Flags::add(c.r[6], c.r[0]).0;
                c.r[0] = Flags::sub(c.r[0], 0x4_u32).0;
                c.r[3] = 0x44_u32;
                {
                    let ea = c.r[10].wrapping_add(c.r[3]);
                    c.r[1] = m.r32(ea);
                }
                c.r[14] = 0x290a00;
                c.f = f;
                f_00290cb4(c, m, h);
                f = c.f;
                f = Flags::sub(c.r[0], 0x0_u32).1;
                if f.z {
                    {
                        let ea = c.r[5].wrapping_add(0x4);
                        m.w32(ea, c.r[0]);
                    }
                }
                pc = 0x290a08;
            }
            0x290a08 => {
                c.r[0] = Flags::add(c.r[5], 0x8_u32).0;
                c.r[1] = c.r[6];
                c.r[14] = 0x290a14;
                c.f = f;
                f_00290888(c, m, h);
                f = c.f;
                f = Flags::sub(c.r[0], 0x0_u32).1;
                if (!f.z && f.n == f.v) {
                    c.r[3] = 0x1_u32;
                }
                if (!f.z && f.n == f.v) {
                    {
                        let ea = c.r[5];
                        m.w8(ea, c.r[3] as u8);
                    }
                }
                c.r[3] = 0x0_u32;
                {
                    let ea = c.r[5].wrapping_add(0x208);
                    m.w32(ea, c.r[3]);
                }
                f = Flags::sub(c.r[8], c.r[3]).1;
                if f.z {
                    c.r[3] = Flags::add(c.r[5], 0x210_u32).0;
                }
                if f.z {
                    c.r[2] = 0x6c_u32;
                }
                if f.z {
                    {
                        let ea = c.r[3];
                        m.w16(ea, c.r[2] as u16);
                    }
                }
                if !f.z {
                    c.r[0] = Flags::add(c.r[5], 0x210_u32).0;
                }
                if !f.z {
                    c.r[1] = c.r[8];
                }
                if !f.z {
                    c.r[14] = 0x290a44;
                    c.f = f;
                    xrt::strcpy(c, m);
                    f = c.f;
                }
                {
                    let ea = c.r[5].wrapping_add(0x20c);
                    m.w32(ea, c.r[9]);
                }
                {
                    let ea = c.r[5];
                    c.r[3] = m.r8(ea) as u32;
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if !f.z {
                    pc = 0x290a78;
                    continue;
                }
                c.r[1] = Flags::add(c.r[5], 0x8_u32).0;
                c.r[0] = c.r[5];
                c.r[14] = 0x290a60;
                c.f = f;
                f_00290d60(c, m, h);
                f = c.f;
                c.r[7] = c.r[0];
                f = Flags::sub(c.r[0], 0x0_u32).1;
                if f.z {
                    pc = 0x290ab0;
                    continue;
                }
                c.r[0] = c.r[5];
                c.r[14] = 0x290a74;
                c.f = f;
                h.import("free", c, m);
                f = c.f;
                pc = 0x290ab0;
                continue;
            }
            0x290a78 => {
                c.r[4] = c.r[13];
                c.r[0] = c.r[5];
                c.r[1] = c.r[13];
                c.r[14] = 0x290a88;
                c.f = f;
                f_00291184(c, m, h);
                f = c.f;
                c.r[0] = c.r[13];
                c.r[3] = 0x48_u32;
                {
                    let ea = c.r[10].wrapping_add(c.r[3]);
                    c.r[1] = m.r32(ea);
                }
                c.r[14] = 0x290a98;
                c.f = f;
                h.import("fopen", c, m);
                f = c.f;
                f = Flags::sub(c.r[0], 0x0_u32).1;
                if f.z {
                    c.r[0] = 0x5_u32;
                }
                if f.z {
                    pc = 0x290ab4;
                    continue;
                }
                c.r[14] = 0x290aa8;
                c.f = f;
                h.import("fclose", c, m);
                f = c.f;
                c.r[0] = c.r[13];
                c.r[14] = 0x290ab0;
                c.f = f;
                h.import("remove", c, m);
                f = c.f;
                pc = 0x290ab0;
            }
            0x290ab0 => {
                c.r[0] = c.r[7];
                pc = 0x290ab4;
            }
            0x290ab4 => {
                c.r[13] = Flags::add(c.r[13], 0x200_u32).0;
                {
                    let b = c.r[13];
                    c.r[4] = m.r32(b.wrapping_add(0x0));
                    c.r[5] = m.r32(b.wrapping_add(0x4));
                    c.r[6] = m.r32(b.wrapping_add(0x8));
                    c.r[7] = m.r32(b.wrapping_add(0xc));
                    c.r[8] = m.r32(b.wrapping_add(0x10));
                    c.r[9] = m.r32(b.wrapping_add(0x14));
                    c.r[10] = m.r32(b.wrapping_add(0x18));
                    c.r[13] = b.wrapping_add(0x20);
                    c.f = f;
                    return;
                }
            }
            _ => unreachable!("f_0029094c: no block at {pc:#x}"),
        }
    }
}

pub fn f_00290ac8(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host) {
    f_00290ac8_at(c, m, h, 0x290ac8)
}

/// Enter at any of this function's blocks. The engine takes the
/// address of code that is not a function start, so an indirect
/// call has to be able to land mid-function.
pub fn f_00290ac8_at(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host, start: u32) {
    let mut pc: u32 = start;
    let mut f = c.f;
    loop {
        #[cfg(feature = "cover")]
        xrt::hit(pc, &c.r);
        match pc {
            0x290ac8 => {
                {
                    let b = c.r[13];
                    m.w32(b.wrapping_add(0xfffffff0), c.r[4]);
                    m.w32(b.wrapping_add(0xfffffff4), c.r[5]);
                    m.w32(b.wrapping_add(0xfffffff8), c.r[10]);
                    m.w32(b.wrapping_add(0xfffffffc), c.r[14]);
                    c.r[13] = b.wrapping_add(0xfffffff0);
                }
                c.r[10] = 0x8914_u32;
                c.r[10] = Flags::add(0x290ad8_u32, c.r[10]).0;
                c.r[5] = 0x0_u32;
                {
                    let (v, g) = Flags::sub(c.r[0], 0x0_u32);
                    f = g;
                    c.r[4] = v;
                }
                if f.z {
                    c.r[0] = c.r[5];
                }
                if f.z {
                    {
                        let b = c.r[13];
                        c.r[4] = m.r32(b.wrapping_add(0x0));
                        c.r[5] = m.r32(b.wrapping_add(0x4));
                        c.r[10] = m.r32(b.wrapping_add(0x8));
                        c.r[13] = b.wrapping_add(0x10);
                        c.f = f;
                        return;
                    }
                }
                c.r[0] = c.r[4];
                c.r[14] = 0x290aec;
                c.f = f;
                f_00291058(c, m, h);
                f = c.f;
                c.r[0] = c.r[4];
                c.r[14] = 0x290af4;
                c.f = f;
                h.import("free", c, m);
                f = c.f;
                c.r[0] = c.r[5];
                {
                    let b = c.r[13];
                    c.r[4] = m.r32(b.wrapping_add(0x0));
                    c.r[5] = m.r32(b.wrapping_add(0x4));
                    c.r[10] = m.r32(b.wrapping_add(0x8));
                    c.r[13] = b.wrapping_add(0x10);
                    c.f = f;
                    return;
                }
            }
            _ => unreachable!("f_00290ac8: no block at {pc:#x}"),
        }
    }
}

pub fn f_00290b00(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host) {
    f_00290b00_at(c, m, h, 0x290b00)
}

/// Enter at any of this function's blocks. The engine takes the
/// address of code that is not a function start, so an indirect
/// call has to be able to land mid-function.
pub fn f_00290b00_at(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host, start: u32) {
    let mut pc: u32 = start;
    let mut f = c.f;
    loop {
        #[cfg(feature = "cover")]
        xrt::hit(pc, &c.r);
        match pc {
            0x290b00 => {
                {
                    let b = c.r[13];
                    m.w32(b.wrapping_add(0xffffffe8), c.r[4]);
                    m.w32(b.wrapping_add(0xffffffec), c.r[5]);
                    m.w32(b.wrapping_add(0xfffffff0), c.r[6]);
                    m.w32(b.wrapping_add(0xfffffff4), c.r[7]);
                    m.w32(b.wrapping_add(0xfffffff8), c.r[10]);
                    m.w32(b.wrapping_add(0xfffffffc), c.r[14]);
                    c.r[13] = b.wrapping_add(0xffffffe8);
                }
                c.r[13] = Flags::sub(c.r[13], 0x200_u32).0;
                c.r[10] = 0x88d8_u32;
                c.r[10] = Flags::add(0x290b14_u32, c.r[10]).0;
                c.r[7] = c.r[1];
                c.r[6] = c.r[2];
                c.r[2] = c.r[3];
                {
                    let (v, g) = Flags::sub(c.r[0], 0x0_u32);
                    f = g;
                    c.r[5] = v;
                }
                if f.z {
                    pc = 0x290ba4;
                    continue;
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if !f.z {
                    c.r[3] = 0x0_u32;
                }
                if !f.z {
                    {
                        let ea = c.r[2];
                        m.w32(ea, c.r[3]);
                    }
                }
                f = Flags::sub(c.r[6], 0x0_u32).1;
                if !f.z {
                    pc = 0x290b50;
                    continue;
                }
                {
                    let ea = c.r[5];
                    c.r[3] = m.r8(ea) as u32;
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if !f.z {
                    c.r[0] = c.r[5];
                }
                if !f.z {
                    c.r[14] = 0x290b48;
                    c.f = f;
                    f_00291058(c, m, h);
                    f = c.f;
                }
                c.r[0] = 0x0_u32;
                pc = 0x290ba4;
                continue;
            }
            0x290b50 => {
                {
                    let ea = c.r[5];
                    c.r[3] = m.r8(ea) as u32;
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if f.z {
                    pc = 0x290b94;
                    continue;
                }
                {
                    let ea = c.r[5].wrapping_add(0x21c);
                    c.r[3] = m.r32(ea);
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if !f.z {
                    pc = 0x290b94;
                    continue;
                }
                c.r[4] = c.r[13];
                c.r[0] = c.r[5];
                c.r[1] = c.r[13];
                c.r[14] = 0x290b78;
                c.f = f;
                f_00291184(c, m, h);
                f = c.f;
                {
                    let ea = c.r[5].wrapping_add(0x208);
                    m.w32(ea, c.r[0]);
                }
                c.r[0] = c.r[5];
                c.r[1] = c.r[13];
                c.r[14] = 0x290b88;
                c.f = f;
                f_00290d60(c, m, h);
                f = c.f;
                f = Flags::sub(c.r[0], 0x0_u32).1;
                if !f.z {
                    c.r[0] = 0x7_u32;
                }
                if !f.z {
                    pc = 0x290ba4;
                    continue;
                }
                pc = 0x290b94;
            }
            0x290b94 => {
                c.r[0] = c.r[5];
                c.r[1] = c.r[7];
                c.r[2] = c.r[6];
                c.r[14] = 0x290ba4;
                c.f = f;
                f_002911dc(c, m, h);
                f = c.f;
                pc = 0x290ba4;
            }
            0x290ba4 => {
                c.r[13] = Flags::add(c.r[13], 0x200_u32).0;
                {
                    let b = c.r[13];
                    c.r[4] = m.r32(b.wrapping_add(0x0));
                    c.r[5] = m.r32(b.wrapping_add(0x4));
                    c.r[6] = m.r32(b.wrapping_add(0x8));
                    c.r[7] = m.r32(b.wrapping_add(0xc));
                    c.r[10] = m.r32(b.wrapping_add(0x10));
                    c.r[13] = b.wrapping_add(0x18);
                    c.f = f;
                    return;
                }
            }
            _ => unreachable!("f_00290b00: no block at {pc:#x}"),
        }
    }
}

pub fn f_00290bb0(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host) {
    f_00290bb0_at(c, m, h, 0x290bb0)
}

/// Enter at any of this function's blocks. The engine takes the
/// address of code that is not a function start, so an indirect
/// call has to be able to land mid-function.
pub fn f_00290bb0_at(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host, start: u32) {
    let mut pc: u32 = start;
    let mut f = c.f;
    loop {
        #[cfg(feature = "cover")]
        xrt::hit(pc, &c.r);
        match pc {
            0x290bb0 => {
                {
                    let b = c.r[13];
                    m.w32(b.wrapping_add(0xfffffff4), c.r[4]);
                    m.w32(b.wrapping_add(0xfffffff8), c.r[10]);
                    m.w32(b.wrapping_add(0xfffffffc), c.r[14]);
                    c.r[13] = b.wrapping_add(0xfffffff4);
                }
                c.r[10] = 0x882c_u32;
                c.r[10] = Flags::add(0x290bc0_u32, c.r[10]).0;
                c.r[4] = 0x0_u32;
                f = Flags::sub(c.r[0], 0x0_u32).1;
                if f.z {
                    c.r[0] = c.r[4];
                }
                if f.z {
                    {
                        let b = c.r[13];
                        c.r[4] = m.r32(b.wrapping_add(0x0));
                        c.r[10] = m.r32(b.wrapping_add(0x4));
                        c.r[13] = b.wrapping_add(0xc);
                        c.f = f;
                        return;
                    }
                }
                {
                    let ea = c.r[0];
                    c.r[3] = m.r8(ea) as u32;
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if !f.z {
                    c.r[14] = 0x290bd8;
                    c.f = f;
                    f_00291058(c, m, h);
                    f = c.f;
                }
                c.r[0] = c.r[4];
                {
                    let b = c.r[13];
                    c.r[4] = m.r32(b.wrapping_add(0x0));
                    c.r[10] = m.r32(b.wrapping_add(0x4));
                    c.r[13] = b.wrapping_add(0xc);
                    c.f = f;
                    return;
                }
            }
            _ => unreachable!("f_00290bb0: no block at {pc:#x}"),
        }
    }
}

pub fn f_00290be4(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host) {
    f_00290be4_at(c, m, h, 0x290be4)
}

/// Enter at any of this function's blocks. The engine takes the
/// address of code that is not a function start, so an indirect
/// call has to be able to land mid-function.
pub fn f_00290be4_at(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host, start: u32) {
    let mut pc: u32 = start;
    let mut f = c.f;
    loop {
        #[cfg(feature = "cover")]
        xrt::hit(pc, &c.r);
        match pc {
            0x290be4 => {
                {
                    let b = c.r[13];
                    m.w32(b.wrapping_add(0xfffffff0), c.r[4]);
                    m.w32(b.wrapping_add(0xfffffff4), c.r[5]);
                    m.w32(b.wrapping_add(0xfffffff8), c.r[10]);
                    m.w32(b.wrapping_add(0xfffffffc), c.r[14]);
                    c.r[13] = b.wrapping_add(0xfffffff0);
                }
                c.r[10] = 0x87f8_u32;
                c.r[10] = Flags::add(0x290bf4_u32, c.r[10]).0;
                c.r[4] = c.r[1];
                c.r[5] = c.r[2];
                f = Flags::sub(c.r[1], 0x0_u32).1;
                if f.z {
                    c.r[0] = 0x2_u32;
                }
                if f.z {
                    {
                        let b = c.r[13];
                        c.r[4] = m.r32(b.wrapping_add(0x0));
                        c.r[5] = m.r32(b.wrapping_add(0x4));
                        c.r[10] = m.r32(b.wrapping_add(0x8));
                        c.r[13] = b.wrapping_add(0x10);
                        c.f = f;
                        return;
                    }
                }
                c.r[3] = Flags::sub(c.r[0], 0x1_u32).0;
                f = Flags::sub(c.r[3], 0x6_u32).1;
                if (!f.c || f.z) {
                    pc = 0x290c14_u32.wrapping_add(c.r[3] << 2);
                    continue;
                }
                pc = 0x290c68;
                continue;
            }
            0x290c14 => {
                pc = 0x290c30;
                continue;
            }
            0x290c18 => {
                pc = 0x290c38;
                continue;
            }
            0x290c1c => {
                pc = 0x290c40;
                continue;
            }
            0x290c20 => {
                pc = 0x290c48;
                continue;
            }
            0x290c24 => {
                pc = 0x290c50;
                continue;
            }
            0x290c28 => {
                pc = 0x290c58;
                continue;
            }
            0x290c2c => {
                pc = 0x290c60;
                continue;
            }
            0x290c30 => {
                c.r[3] = 0x4c_u32;
                pc = 0x290c6c;
                continue;
            }
            0x290c38 => {
                c.r[3] = 0x50_u32;
                pc = 0x290c6c;
                continue;
            }
            0x290c40 => {
                c.r[3] = 0x54_u32;
                pc = 0x290c6c;
                continue;
            }
            0x290c48 => {
                c.r[3] = 0x58_u32;
                pc = 0x290c6c;
                continue;
            }
            0x290c50 => {
                c.r[3] = 0x5c_u32;
                pc = 0x290c6c;
                continue;
            }
            0x290c58 => {
                c.r[3] = 0x60_u32;
                pc = 0x290c6c;
                continue;
            }
            0x290c60 => {
                c.r[3] = 0x64_u32;
                pc = 0x290c6c;
                continue;
            }
            0x290c68 => {
                c.r[3] = 0x68_u32;
                pc = 0x290c6c;
            }
            0x290c6c => {
                {
                    let ea = c.r[10].wrapping_add(c.r[3]);
                    c.r[1] = m.r32(ea);
                }
                c.r[2] = Flags::sub(c.r[5], 0x1_u32).0;
                c.r[0] = c.r[4];
                c.r[14] = 0x290c7c;
                c.f = f;
                xrt::strncpy(c, m);
                f = c.f;
                c.r[2] = Flags::add(c.r[4], c.r[5]).0;
                c.r[3] = 0x0_u32;
                {
                    let ea = c.r[2].wrapping_sub(0x1);
                    m.w8(ea, c.r[3] as u8);
                }
                c.r[0] = c.r[3];
                {
                    let b = c.r[13];
                    c.r[4] = m.r32(b.wrapping_add(0x0));
                    c.r[5] = m.r32(b.wrapping_add(0x4));
                    c.r[10] = m.r32(b.wrapping_add(0x8));
                    c.r[13] = b.wrapping_add(0x10);
                    c.f = f;
                    return;
                }
            }
            _ => unreachable!("f_00290be4: no block at {pc:#x}"),
        }
    }
}

pub fn f_00290cb4(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host) {
    f_00290cb4_at(c, m, h, 0x290cb4)
}

/// Enter at any of this function's blocks. The engine takes the
/// address of code that is not a function start, so an indirect
/// call has to be able to land mid-function.
pub fn f_00290cb4_at(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host, start: u32) {
    let mut pc: u32 = start;
    let mut f = c.f;
    loop {
        #[cfg(feature = "cover")]
        xrt::hit(pc, &c.r);
        match pc {
            0x290cb4 => {
                {
                    let b = c.r[13];
                    m.w32(b.wrapping_add(0xfffffff8), c.r[4]);
                    m.w32(b.wrapping_add(0xfffffffc), c.r[14]);
                    c.r[13] = b.wrapping_add(0xfffffff8);
                }
                c.r[4] = c.r[0];
                c.r[14] = c.r[1];
                c.r[1] = 0x0_u32;
                {
                    let ea = c.r[0].wrapping_add(c.r[1]);
                    c.r[3] = m.r8(ea) as u32;
                }
                c.r[2] = c.r[3];
                f = Flags::sub(c.r[3], c.r[1]).1;
                if f.z {
                    pc = 0x290d4c;
                    continue;
                }
                {
                    let ea = c.r[14].wrapping_add(c.r[1]);
                    c.r[3] = m.r8(ea) as u32;
                }
                f = Flags::sub(c.r[3], c.r[1]).1;
                if f.z {
                    pc = 0x290d3c;
                    continue;
                }
                pc = 0x290ce0;
            }
            0x290ce0 => {
                c.r[3] = Flags::sub(c.r[2], 0x41_u32).0;
                f = Flags::sub(c.r[3], 0x19_u32).1;
                if (!f.c || f.z) {
                    c.r[3] = Flags::add(c.r[2], 0x20_u32).0;
                }
                if (!f.c || f.z) {
                    c.r[12] = c.r[3] & 0xff_u32;
                }
                if (f.c && !f.z) {
                    {
                        let ea = c.r[4].wrapping_add(c.r[1]);
                        c.r[12] = m.r8(ea) as u32;
                    }
                }
                {
                    let ea = c.r[14].wrapping_add(c.r[1]);
                    c.r[2] = m.r8(ea) as u32;
                }
                c.r[3] = Flags::sub(c.r[2], 0x41_u32).0;
                f = Flags::sub(c.r[3], 0x19_u32).1;
                if (!f.c || f.z) {
                    c.r[3] = Flags::add(c.r[2], 0x20_u32).0;
                }
                if (!f.c || f.z) {
                    c.r[3] = c.r[3] & 0xff_u32;
                }
                if (f.c && !f.z) {
                    {
                        let ea = c.r[14].wrapping_add(c.r[1]);
                        c.r[3] = m.r8(ea) as u32;
                    }
                }
                c.r[0] = Flags::sub(c.r[12], c.r[3]).0;
                f = Flags::sub(c.r[0], 0x0_u32).1;
                if !f.z {
                    {
                        let b = c.r[13];
                        c.r[4] = m.r32(b.wrapping_add(0x0));
                        c.r[13] = b.wrapping_add(0x8);
                        c.f = f;
                        return;
                    }
                }
                c.r[3] = Flags::add(c.r[1], 0x1_u32).0;
                c.r[3] = (c.r[3] << 16);
                c.r[1] = (c.r[3] >> 16);
                {
                    let ea = c.r[4].wrapping_add(c.r[1]);
                    c.r[2] = m.r8(ea) as u32;
                }
                f = Flags::sub(c.r[2], 0x0_u32).1;
                if f.z {
                    pc = 0x290d4c;
                    continue;
                }
                {
                    let ea = c.r[14].wrapping_add(c.r[1]);
                    c.r[3] = m.r8(ea) as u32;
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if !f.z {
                    pc = 0x290ce0;
                    continue;
                }
                pc = 0x290d3c;
            }
            0x290d3c => {
                {
                    let ea = c.r[4].wrapping_add(c.r[1]);
                    c.r[3] = m.r8(ea) as u32;
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if !f.z {
                    c.r[0] = 0x1_u32;
                }
                if !f.z {
                    {
                        let b = c.r[13];
                        c.r[4] = m.r32(b.wrapping_add(0x0));
                        c.r[13] = b.wrapping_add(0x8);
                        c.f = f;
                        return;
                    }
                }
                pc = 0x290d4c;
            }
            0x290d4c => {
                {
                    let ea = c.r[14].wrapping_add(c.r[1]);
                    c.r[3] = m.r8(ea) as u32;
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if !f.z {
                    c.r[0] = !0x0_u32;
                }
                if f.z {
                    c.r[0] = 0x0_u32;
                }
                {
                    let b = c.r[13];
                    c.r[4] = m.r32(b.wrapping_add(0x0));
                    c.r[13] = b.wrapping_add(0x8);
                    c.f = f;
                    return;
                }
            }
            _ => unreachable!("f_00290cb4: no block at {pc:#x}"),
        }
    }
}

pub fn f_00290d60(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host) {
    f_00290d60_at(c, m, h, 0x290d60)
}

/// Enter at any of this function's blocks. The engine takes the
/// address of code that is not a function start, so an indirect
/// call has to be able to land mid-function.
pub fn f_00290d60_at(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host, start: u32) {
    let mut pc: u32 = start;
    let mut f = c.f;
    loop {
        #[cfg(feature = "cover")]
        xrt::hit(pc, &c.r);
        match pc {
            0x290d60 => {
                {
                    let b = c.r[13];
                    m.w32(b.wrapping_add(0xffffffe8), c.r[4]);
                    m.w32(b.wrapping_add(0xffffffec), c.r[5]);
                    m.w32(b.wrapping_add(0xfffffff0), c.r[6]);
                    m.w32(b.wrapping_add(0xfffffff4), c.r[7]);
                    m.w32(b.wrapping_add(0xfffffff8), c.r[10]);
                    m.w32(b.wrapping_add(0xfffffffc), c.r[14]);
                    c.r[13] = b.wrapping_add(0xffffffe8);
                }
                c.r[10] = 0x867c_u32;
                c.r[10] = Flags::add(0x290d70_u32, c.r[10]).0;
                c.r[6] = c.r[0];
                c.r[7] = c.r[1];
                {
                    let ea = c.r[0].wrapping_add(0x4);
                    c.r[5] = m.r32(ea);
                }
                f = Flags::sub(c.r[5], 0x0_u32).1;
                if !f.z {
                    pc = 0x291010;
                    continue;
                }
                c.r[4] = Flags::add(c.r[0], 0x220_u32).0;
                c.r[0] = c.r[4];
                c.r[1] = c.r[5];
                c.r[2] = 0x40_u32;
                c.r[14] = 0x290d94;
                c.f = f;
                xrt::memset(c, m);
                f = c.f;
                {
                    let ea = c.r[4];
                    m.w8(ea, c.r[5] as u8);
                }
                c.r[3] = 0x46464952_u32;
                {
                    let ea = c.r[6].wrapping_add(0x224);
                    m.w32(ea, c.r[3]);
                }
                c.r[3] = 0x45564157_u32;
                {
                    let ea = c.r[6].wrapping_add(0x22c);
                    m.w32(ea, c.r[3]);
                }
                c.r[3] = 0x20746d66_u32;
                {
                    let ea = c.r[6].wrapping_add(0x230);
                    m.w32(ea, c.r[3]);
                }
                c.r[3] = 0x61746164_u32;
                {
                    let ea = c.r[6].wrapping_add(0x258);
                    m.w32(ea, c.r[3]);
                }
                c.r[0] = Flags::add(c.r[6], 0x248_u32).0;
                c.r[0] = Flags::add(c.r[0], 0x2_u32).0;
                c.r[3] = 0x6c_u32;
                {
                    let ea = c.r[10].wrapping_add(c.r[3]);
                    c.r[1] = m.r32(ea);
                }
                c.r[2] = 0x4_u32;
                c.r[14] = 0x290dd0;
                c.f = f;
                xrt::memcpy(c, m);
                f = c.f;
                c.r[3] = Flags::add(c.r[6], 0x238_u32).0;
                c.r[3] = Flags::add(c.r[3], 0x2_u32).0;
                c.r[2] = 0x1_u32;
                {
                    let ea = c.r[3];
                    m.w8(ea, c.r[2] as u8);
                }
                c.r[3] = Flags::add(c.r[6], 0x20c_u32).0;
                {
                    let ea = c.r[3];
                    c.r[3] = m.r8(ea) as u32;
                }
                c.r[1] = c.r[6];
                {
                    let ea = c.r[1].wrapping_add(0x23c);
                    let nb = c.r[1].wrapping_add(0x23c);
                    m.w8(ea, c.r[3] as u8);
                    c.r[1] = nb;
                }
                {
                    let ea = c.r[6].wrapping_add(0x20c);
                    c.r[3] = m.r32(ea);
                }
                c.r[2] = (c.r[3] >> 8);
                {
                    let ea = c.r[1].wrapping_add(0x1);
                    m.w8(ea, c.r[2] as u8);
                }
                c.r[2] = (c.r[3] >> 16);
                {
                    let ea = c.r[1].wrapping_add(0x2);
                    m.w8(ea, c.r[2] as u8);
                }
                c.r[3] = (c.r[3] >> 24);
                {
                    let ea = c.r[1].wrapping_add(0x3);
                    m.w8(ea, c.r[3] as u8);
                }
                c.r[3] = Flags::add(c.r[6], 0x210_u32).0;
                {
                    let ea = c.r[3];
                    c.r[3] = m.r8(ea) as u32;
                }
                f = Flags::sub(c.r[3], 0x55_u32).1;
                if f.z {
                    pc = 0x290ef4;
                    continue;
                }
                if (!f.z && f.n == f.v) {
                    pc = 0x290e40;
                    continue;
                }
                f = Flags::sub(c.r[3], 0x41_u32).1;
                if f.z {
                    pc = 0x290ec0;
                    continue;
                }
                if (!f.z && f.n == f.v) {
                    pc = 0x290e34;
                    continue;
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                pc = 0x290e38;
                continue;
            }
            0x290e34 => {
                f = Flags::sub(c.r[3], 0x4c_u32).1;
                pc = 0x290e38;
            }
            0x290e38 => {
                if f.z {
                    pc = 0x290e64;
                    continue;
                }
                pc = 0x290f70;
                continue;
            }
            0x290e40 => {
                f = Flags::sub(c.r[3], 0x6c_u32).1;
                if f.z {
                    pc = 0x290e64;
                    continue;
                }
                if (!f.z && f.n == f.v) {
                    pc = 0x290e58;
                    continue;
                }
                f = Flags::sub(c.r[3], 0x61_u32).1;
                if f.z {
                    pc = 0x290ec0;
                    continue;
                }
                pc = 0x290f70;
                continue;
            }
            0x290e58 => {
                f = Flags::sub(c.r[3], 0x75_u32).1;
                if f.z {
                    pc = 0x290ef4;
                    continue;
                }
                pc = 0x290f70;
                continue;
            }
            0x290e64 => {
                c.r[3] = Flags::add(c.r[6], 0x234_u32).0;
                c.r[0] = 0x10_u32;
                {
                    let ea = c.r[3];
                    m.w8(ea, c.r[0] as u8);
                }
                c.r[2] = Flags::add(c.r[6], 0x238_u32).0;
                c.r[3] = 0x1_u32;
                {
                    let ea = c.r[2];
                    m.w8(ea, c.r[3] as u8);
                }
                {
                    let ea = c.r[6].wrapping_add(0x20c);
                    c.r[3] = m.r32(ea);
                }
                c.r[3] = (c.r[3] << 1);
                c.r[1] = c.r[6];
                {
                    let ea = c.r[1].wrapping_add(0x240);
                    let nb = c.r[1].wrapping_add(0x240);
                    m.w8(ea, c.r[3] as u8);
                    c.r[1] = nb;
                }
                c.r[2] = (c.r[3] >> 8);
                {
                    let ea = c.r[1].wrapping_add(0x1);
                    m.w8(ea, c.r[2] as u8);
                }
                c.r[2] = xrt::shift_reg(1, c.r[3], c.r[0], f.c).0;
                {
                    let ea = c.r[1].wrapping_add(0x2);
                    m.w8(ea, c.r[2] as u8);
                }
                c.r[3] = (c.r[3] >> 24);
                {
                    let ea = c.r[1].wrapping_add(0x3);
                    m.w8(ea, c.r[3] as u8);
                }
                c.r[3] = Flags::add(c.r[6], 0x244_u32).0;
                c.r[3] = Flags::add(c.r[3], 0x2_u32).0;
                {
                    let ea = c.r[3];
                    m.w8(ea, c.r[0] as u8);
                }
                c.r[2] = Flags::add(c.r[6], 0x244_u32).0;
                c.r[3] = 0x2_u32;
                {
                    let ea = c.r[2];
                    m.w8(ea, c.r[3] as u8);
                }
                pc = 0x290f78;
                continue;
            }
            0x290ec0 => {
                c.r[3] = Flags::add(c.r[6], 0x220_u32).0;
                c.r[0] = 0x1_u32;
                {
                    let ea = c.r[3];
                    m.w8(ea, c.r[0] as u8);
                }
                c.r[2] = Flags::add(c.r[6], 0x234_u32).0;
                c.r[3] = 0x12_u32;
                {
                    let ea = c.r[2];
                    m.w8(ea, c.r[3] as u8);
                }
                c.r[3] = Flags::add(c.r[6], 0x24c_u32).0;
                c.r[3] = Flags::add(c.r[3], 0x2_u32).0;
                c.r[2] = 0x4_u32;
                {
                    let ea = c.r[3];
                    m.w8(ea, c.r[2] as u8);
                }
                c.r[2] = Flags::add(c.r[6], 0x238_u32).0;
                c.r[3] = 0x6_u32;
                pc = 0x290f24;
                continue;
            }
            0x290ef4 => {
                c.r[3] = Flags::add(c.r[6], 0x220_u32).0;
                c.r[0] = 0x1_u32;
                {
                    let ea = c.r[3];
                    m.w8(ea, c.r[0] as u8);
                }
                c.r[3] = Flags::add(c.r[6], 0x24c_u32).0;
                c.r[3] = Flags::add(c.r[3], 0x2_u32).0;
                c.r[2] = 0x4_u32;
                {
                    let ea = c.r[3];
                    m.w8(ea, c.r[2] as u8);
                }
                c.r[2] = Flags::add(c.r[6], 0x234_u32).0;
                c.r[3] = 0x12_u32;
                {
                    let ea = c.r[2];
                    m.w8(ea, c.r[3] as u8);
                }
                c.r[2] = Flags::add(c.r[6], 0x238_u32).0;
                c.r[3] = 0x7_u32;
                pc = 0x290f24;
            }
            0x290f24 => {
                {
                    let ea = c.r[2];
                    m.w8(ea, c.r[3] as u8);
                }
                c.r[3] = Flags::add(c.r[6], 0x20c_u32).0;
                {
                    let ea = c.r[3];
                    c.r[3] = m.r8(ea) as u32;
                }
                c.r[1] = c.r[6];
                {
                    let ea = c.r[1].wrapping_add(0x240);
                    let nb = c.r[1].wrapping_add(0x240);
                    m.w8(ea, c.r[3] as u8);
                    c.r[1] = nb;
                }
                {
                    let ea = c.r[6].wrapping_add(0x20c);
                    c.r[3] = m.r32(ea);
                }
                c.r[2] = (c.r[3] >> 8);
                {
                    let ea = c.r[1].wrapping_add(0x1);
                    m.w8(ea, c.r[2] as u8);
                }
                c.r[2] = (c.r[3] >> 16);
                {
                    let ea = c.r[1].wrapping_add(0x2);
                    m.w8(ea, c.r[2] as u8);
                }
                c.r[3] = (c.r[3] >> 24);
                {
                    let ea = c.r[1].wrapping_add(0x3);
                    m.w8(ea, c.r[3] as u8);
                }
                c.r[3] = Flags::add(c.r[6], 0x244_u32).0;
                c.r[3] = Flags::add(c.r[3], 0x2_u32).0;
                c.r[2] = 0x8_u32;
                {
                    let ea = c.r[3];
                    m.w8(ea, c.r[2] as u8);
                }
                c.r[3] = Flags::add(c.r[6], 0x244_u32).0;
                {
                    let ea = c.r[3];
                    m.w8(ea, c.r[0] as u8);
                }
                pc = 0x290f78;
                continue;
            }
            0x290f70 => {
                c.r[0] = 0x6_u32;
                {
                    let b = c.r[13];
                    c.r[4] = m.r32(b.wrapping_add(0x0));
                    c.r[5] = m.r32(b.wrapping_add(0x4));
                    c.r[6] = m.r32(b.wrapping_add(0x8));
                    c.r[7] = m.r32(b.wrapping_add(0xc));
                    c.r[10] = m.r32(b.wrapping_add(0x10));
                    c.r[13] = b.wrapping_add(0x18);
                    c.f = f;
                    return;
                }
            }
            0x290f78 => {
                c.r[0] = c.r[7];
                c.r[3] = 0x70_u32;
                {
                    let ea = c.r[10].wrapping_add(c.r[3]);
                    c.r[1] = m.r32(ea);
                }
                c.r[14] = 0x290f88;
                c.f = f;
                h.import("fopen", c, m);
                f = c.f;
                {
                    let ea = c.r[6].wrapping_add(0x21c);
                    m.w32(ea, c.r[0]);
                }
                f = Flags::sub(c.r[0], 0x0_u32).1;
                if f.z {
                    pc = 0x29102c;
                    continue;
                }
                c.r[0] = Flags::add(c.r[6], 0x224_u32).0;
                c.r[1] = 0x1_u32;
                c.r[2] = 0x24_u32;
                {
                    let ea = c.r[6].wrapping_add(0x21c);
                    c.r[3] = m.r32(ea);
                }
                c.r[14] = 0x290fa8;
                c.f = f;
                h.import("fwrite", c, m);
                f = c.f;
                f = Flags::sub(c.r[0], 0x24_u32).1;
                if !f.z {
                    pc = 0x290ff8;
                    continue;
                }
                c.r[3] = Flags::add(c.r[6], 0x220_u32).0;
                {
                    let ea = c.r[3];
                    c.r[3] = m.r8(ea) as u32;
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if f.z {
                    pc = 0x290fdc;
                    continue;
                }
                c.r[0] = Flags::add(c.r[6], 0x248_u32).0;
                c.r[1] = 0x1_u32;
                c.r[2] = 0x10_u32;
                {
                    let ea = c.r[6].wrapping_add(0x21c);
                    c.r[3] = m.r32(ea);
                }
                c.r[14] = 0x290fd4;
                c.f = f;
                h.import("fwrite", c, m);
                f = c.f;
                f = Flags::sub(c.r[0], 0x10_u32).1;
                if !f.z {
                    pc = 0x290ff8;
                    continue;
                }
                pc = 0x290fdc;
            }
            0x290fdc => {
                c.r[0] = Flags::add(c.r[6], 0x258_u32).0;
                c.r[1] = 0x1_u32;
                c.r[2] = 0x8_u32;
                {
                    let ea = c.r[6].wrapping_add(0x21c);
                    c.r[3] = m.r32(ea);
                }
                c.r[14] = 0x290ff0;
                c.f = f;
                h.import("fwrite", c, m);
                f = c.f;
                f = Flags::sub(c.r[0], 0x8_u32).1;
                if f.z {
                    pc = 0x291034;
                    continue;
                }
                pc = 0x290ff8;
            }
            0x290ff8 => {
                {
                    let ea = c.r[6].wrapping_add(0x21c);
                    c.r[0] = m.r32(ea);
                }
                c.r[14] = 0x291000;
                c.f = f;
                h.import("fclose", c, m);
                f = c.f;
                c.r[3] = 0x0_u32;
                {
                    let ea = c.r[6].wrapping_add(0x21c);
                    m.w32(ea, c.r[3]);
                }
                c.r[0] = 0x7_u32;
                {
                    let b = c.r[13];
                    c.r[4] = m.r32(b.wrapping_add(0x0));
                    c.r[5] = m.r32(b.wrapping_add(0x4));
                    c.r[6] = m.r32(b.wrapping_add(0x8));
                    c.r[7] = m.r32(b.wrapping_add(0xc));
                    c.r[10] = m.r32(b.wrapping_add(0x10));
                    c.r[13] = b.wrapping_add(0x18);
                    c.f = f;
                    return;
                }
            }
            0x291010 => {
                c.r[0] = c.r[1];
                c.r[3] = 0x70_u32;
                {
                    let ea = c.r[10].wrapping_add(c.r[3]);
                    c.r[1] = m.r32(ea);
                }
                c.r[14] = 0x291020;
                c.f = f;
                h.import("fopen", c, m);
                f = c.f;
                {
                    let ea = c.r[6].wrapping_add(0x21c);
                    m.w32(ea, c.r[0]);
                }
                f = Flags::sub(c.r[0], 0x0_u32).1;
                if !f.z {
                    pc = 0x291034;
                    continue;
                }
                pc = 0x29102c;
            }
            0x29102c => {
                c.r[0] = 0x5_u32;
                {
                    let b = c.r[13];
                    c.r[4] = m.r32(b.wrapping_add(0x0));
                    c.r[5] = m.r32(b.wrapping_add(0x4));
                    c.r[6] = m.r32(b.wrapping_add(0x8));
                    c.r[7] = m.r32(b.wrapping_add(0xc));
                    c.r[10] = m.r32(b.wrapping_add(0x10));
                    c.r[13] = b.wrapping_add(0x18);
                    c.f = f;
                    return;
                }
            }
            0x291034 => {
                c.r[0] = 0x0_u32;
                {
                    let b = c.r[13];
                    c.r[4] = m.r32(b.wrapping_add(0x0));
                    c.r[5] = m.r32(b.wrapping_add(0x4));
                    c.r[6] = m.r32(b.wrapping_add(0x8));
                    c.r[7] = m.r32(b.wrapping_add(0xc));
                    c.r[10] = m.r32(b.wrapping_add(0x10));
                    c.r[13] = b.wrapping_add(0x18);
                    c.f = f;
                    return;
                }
            }
            _ => unreachable!("f_00290d60: no block at {pc:#x}"),
        }
    }
}

pub fn f_00291058(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host) {
    f_00291058_at(c, m, h, 0x291058)
}

/// Enter at any of this function's blocks. The engine takes the
/// address of code that is not a function start, so an indirect
/// call has to be able to land mid-function.
pub fn f_00291058_at(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host, start: u32) {
    let mut pc: u32 = start;
    let mut f = c.f;
    loop {
        #[cfg(feature = "cover")]
        xrt::hit(pc, &c.r);
        match pc {
            0x291058 => {
                {
                    let b = c.r[13];
                    m.w32(b.wrapping_add(0xfffffff8), c.r[4]);
                    m.w32(b.wrapping_add(0xfffffffc), c.r[14]);
                    c.r[13] = b.wrapping_add(0xfffffff8);
                }
                c.r[4] = c.r[0];
                {
                    let ea = c.r[0].wrapping_add(0x4);
                    c.r[3] = m.r32(ea);
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if !f.z {
                    pc = 0x29116c;
                    continue;
                }
                {
                    let ea = c.r[0].wrapping_add(0x21c);
                    c.r[0] = m.r32(ea);
                }
                f = Flags::sub(c.r[0], 0x0_u32).1;
                if f.z {
                    pc = 0x291178;
                    continue;
                }
                c.r[14] = 0x29107c;
                c.f = f;
                h.import("rewind", c, m);
                f = c.f;
                {
                    let ea = c.r[4].wrapping_add(0x260);
                    c.r[2] = m.r32(ea);
                }
                c.r[1] = Flags::add(c.r[2], 0x24_u32).0;
                c.r[3] = Flags::add(c.r[4], 0x220_u32).0;
                {
                    let ea = c.r[3];
                    c.r[3] = m.r8(ea) as u32;
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if !f.z {
                    c.r[1] = Flags::add(c.r[2], 0x34_u32).0;
                }
                c.r[2] = c.r[4];
                {
                    let ea = c.r[2].wrapping_add(0x228);
                    let nb = c.r[2].wrapping_add(0x228);
                    m.w8(ea, c.r[1] as u8);
                    c.r[2] = nb;
                }
                c.r[3] = (c.r[1] >> 8);
                {
                    let ea = c.r[2].wrapping_add(0x1);
                    m.w8(ea, c.r[3] as u8);
                }
                c.r[3] = (c.r[1] >> 16);
                {
                    let ea = c.r[2].wrapping_add(0x2);
                    m.w8(ea, c.r[3] as u8);
                }
                c.r[3] = (c.r[1] >> 24);
                {
                    let ea = c.r[2].wrapping_add(0x3);
                    m.w8(ea, c.r[3] as u8);
                }
                c.r[2] = Flags::add(c.r[4], 0x250_u32).0;
                c.r[2] = Flags::add(c.r[2], 0x2_u32).0;
                c.r[3] = Flags::add(c.r[4], 0x260_u32).0;
                {
                    let ea = c.r[3];
                    c.r[3] = m.r8(ea) as u32;
                }
                c.r[0] = c.r[4];
                {
                    let ea = c.r[0].wrapping_add(0x25c);
                    let nb = c.r[0].wrapping_add(0x25c);
                    m.w8(ea, c.r[3] as u8);
                    c.r[0] = nb;
                }
                {
                    let ea = c.r[2];
                    m.w8(ea, c.r[3] as u8);
                }
                c.r[2] = Flags::add(c.r[4], 0x250_u32).0;
                c.r[2] = Flags::add(c.r[2], 0x3_u32).0;
                {
                    let ea = c.r[4].wrapping_add(0x260);
                    c.r[1] = m.r32(ea);
                }
                c.r[3] = c.r[1] & 0xff00_u32;
                c.r[3] = (c.r[3] >> 8);
                {
                    let ea = c.r[0].wrapping_add(0x1);
                    m.w8(ea, c.r[3] as u8);
                }
                {
                    let ea = c.r[2];
                    m.w8(ea, c.r[3] as u8);
                }
                c.r[3] = c.r[1] & 0xff0000_u32;
                c.r[3] = (c.r[3] >> 16);
                {
                    let ea = c.r[0].wrapping_add(0x2);
                    m.w8(ea, c.r[3] as u8);
                }
                c.r[2] = c.r[4];
                {
                    let ea = c.r[2].wrapping_add(0x254);
                    let nb = c.r[2].wrapping_add(0x254);
                    m.w8(ea, c.r[3] as u8);
                    c.r[2] = nb;
                }
                c.r[1] = (c.r[1] >> 24);
                {
                    let ea = c.r[0].wrapping_add(0x3);
                    m.w8(ea, c.r[1] as u8);
                }
                {
                    let ea = c.r[2].wrapping_add(0x1);
                    m.w8(ea, c.r[1] as u8);
                }
                c.r[0] = Flags::add(c.r[4], 0x224_u32).0;
                c.r[1] = 0x1_u32;
                c.r[2] = 0x24_u32;
                {
                    let ea = c.r[4].wrapping_add(0x21c);
                    c.r[3] = m.r32(ea);
                }
                c.r[14] = 0x291120;
                c.f = f;
                h.import("fwrite", c, m);
                f = c.f;
                c.r[3] = Flags::add(c.r[4], 0x220_u32).0;
                {
                    let ea = c.r[3];
                    c.r[3] = m.r8(ea) as u32;
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if f.z {
                    pc = 0x291144;
                    continue;
                }
                c.r[0] = Flags::add(c.r[4], 0x248_u32).0;
                c.r[1] = 0x1_u32;
                c.r[2] = 0x10_u32;
                {
                    let ea = c.r[4].wrapping_add(0x21c);
                    c.r[3] = m.r32(ea);
                }
                c.r[14] = 0x291144;
                c.f = f;
                h.import("fwrite", c, m);
                f = c.f;
                pc = 0x291144;
            }
            0x291144 => {
                c.r[0] = Flags::add(c.r[4], 0x258_u32).0;
                c.r[1] = 0x1_u32;
                c.r[2] = 0x8_u32;
                {
                    let ea = c.r[4].wrapping_add(0x21c);
                    c.r[3] = m.r32(ea);
                }
                c.r[14] = 0x291158;
                c.f = f;
                h.import("fwrite", c, m);
                f = c.f;
                {
                    let ea = c.r[4].wrapping_add(0x21c);
                    c.r[0] = m.r32(ea);
                }
                c.r[14] = 0x291160;
                c.f = f;
                h.import("fclose", c, m);
                f = c.f;
                c.r[3] = 0x0_u32;
                {
                    let ea = c.r[4].wrapping_add(0x21c);
                    m.w32(ea, c.r[3]);
                }
                pc = 0x291178;
                continue;
            }
            0x29116c => {
                {
                    let ea = c.r[0].wrapping_add(0x21c);
                    c.r[0] = m.r32(ea);
                }
                f = Flags::sub(c.r[0], 0x0_u32).1;
                if !f.z {
                    c.r[14] = 0x291178;
                    c.f = f;
                    h.import("fclose", c, m);
                    f = c.f;
                }
                pc = 0x291178;
            }
            0x291178 => {
                c.r[3] = 0x0_u32;
                {
                    let ea = c.r[4].wrapping_add(0x21c);
                    m.w32(ea, c.r[3]);
                }
                {
                    let b = c.r[13];
                    c.r[4] = m.r32(b.wrapping_add(0x0));
                    c.r[13] = b.wrapping_add(0x8);
                    c.f = f;
                    return;
                }
            }
            _ => unreachable!("f_00291058: no block at {pc:#x}"),
        }
    }
}

pub fn f_00291184(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host) {
    f_00291184_at(c, m, h, 0x291184)
}

/// Enter at any of this function's blocks. The engine takes the
/// address of code that is not a function start, so an indirect
/// call has to be able to land mid-function.
pub fn f_00291184_at(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host, start: u32) {
    let mut pc: u32 = start;
    let mut f = c.f;
    loop {
        #[cfg(feature = "cover")]
        xrt::hit(pc, &c.r);
        match pc {
            0x291184 => {
                {
                    let b = c.r[13];
                    m.w32(b.wrapping_add(0xffffffe8), c.r[4]);
                    m.w32(b.wrapping_add(0xffffffec), c.r[5]);
                    m.w32(b.wrapping_add(0xfffffff0), c.r[6]);
                    m.w32(b.wrapping_add(0xfffffff4), c.r[7]);
                    m.w32(b.wrapping_add(0xfffffff8), c.r[10]);
                    m.w32(b.wrapping_add(0xfffffffc), c.r[14]);
                    c.r[13] = b.wrapping_add(0xffffffe8);
                }
                c.r[10] = 0x8258_u32;
                c.r[10] = Flags::add(0x291194_u32, c.r[10]).0;
                c.r[6] = c.r[0];
                c.r[5] = c.r[1];
                {
                    let ea = c.r[0].wrapping_add(0x208);
                    c.r[4] = m.r32(ea);
                }
                c.r[7] = 0x74_u32;
                pc = 0x2911a0;
            }
            0x2911a0 => {
                c.r[4] = Flags::add(c.r[4], 0x1_u32).0;
                c.r[0] = c.r[5];
                c.r[1] = Flags::add(c.r[6], 0x8_u32).0;
                c.r[2] = c.r[4];
                c.r[14] = 0x2911b4;
                c.f = f;
                h.import("sprintf", c, m);
                f = c.f;
                c.r[0] = c.r[5];
                {
                    let ea = c.r[10].wrapping_add(c.r[7]);
                    c.r[1] = m.r32(ea);
                }
                c.r[14] = 0x2911c0;
                c.f = f;
                h.import("fopen", c, m);
                f = c.f;
                f = Flags::sub(c.r[0], 0x0_u32).1;
                if f.z {
                    c.r[0] = c.r[4];
                }
                if f.z {
                    {
                        let b = c.r[13];
                        c.r[4] = m.r32(b.wrapping_add(0x0));
                        c.r[5] = m.r32(b.wrapping_add(0x4));
                        c.r[6] = m.r32(b.wrapping_add(0x8));
                        c.r[7] = m.r32(b.wrapping_add(0xc));
                        c.r[10] = m.r32(b.wrapping_add(0x10));
                        c.r[13] = b.wrapping_add(0x18);
                        c.f = f;
                        return;
                    }
                }
                c.r[14] = 0x2911d0;
                c.f = f;
                h.import("fclose", c, m);
                f = c.f;
                pc = 0x2911a0;
                continue;
            }
            _ => unreachable!("f_00291184: no block at {pc:#x}"),
        }
    }
}

pub fn f_002911dc(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host) {
    f_002911dc_at(c, m, h, 0x2911dc)
}

/// Enter at any of this function's blocks. The engine takes the
/// address of code that is not a function start, so an indirect
/// call has to be able to land mid-function.
pub fn f_002911dc_at(c: &mut Cpu, m: &mut Mem, h: &mut dyn Host, start: u32) {
    let mut pc: u32 = start;
    let mut f = c.f;
    loop {
        #[cfg(feature = "cover")]
        xrt::hit(pc, &c.r);
        match pc {
            0x2911dc => {
                {
                    let b = c.r[13];
                    m.w32(b.wrapping_add(0xfffffff4), c.r[4]);
                    m.w32(b.wrapping_add(0xfffffff8), c.r[5]);
                    m.w32(b.wrapping_add(0xfffffffc), c.r[14]);
                    c.r[13] = b.wrapping_add(0xfffffff4);
                }
                c.r[4] = c.r[0];
                c.r[5] = c.r[2];
                {
                    let ea = c.r[0].wrapping_add(0x4);
                    c.r[0] = m.r32(ea);
                }
                f = Flags::sub(c.r[0], 0x0_u32).1;
                if !f.z {
                    pc = 0x291224;
                    continue;
                }
                {
                    let ea = c.r[4].wrapping_add(0x21c);
                    c.r[3] = m.r32(ea);
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if f.z {
                    pc = 0x291214;
                    continue;
                }
                c.r[0] = c.r[1];
                c.r[1] = 0x1_u32;
                c.r[14] = 0x29120c;
                c.f = f;
                h.import("fwrite", c, m);
                f = c.f;
                f = Flags::sub(c.r[0], c.r[5]).1;
                if !f.z {
                    pc = 0x291244;
                    continue;
                }
                pc = 0x291214;
            }
            0x291214 => {
                {
                    let ea = c.r[4].wrapping_add(0x260);
                    c.r[3] = m.r32(ea);
                }
                c.r[3] = Flags::add(c.r[0], c.r[3]).0;
                {
                    let ea = c.r[4].wrapping_add(0x260);
                    m.w32(ea, c.r[3]);
                }
                pc = 0x29124c;
                continue;
            }
            0x291224 => {
                {
                    let ea = c.r[4].wrapping_add(0x21c);
                    c.r[3] = m.r32(ea);
                }
                f = Flags::sub(c.r[3], 0x0_u32).1;
                if f.z {
                    pc = 0x29124c;
                    continue;
                }
                c.r[0] = c.r[1];
                c.r[1] = 0x1_u32;
                c.r[14] = 0x29123c;
                c.f = f;
                h.import("fwrite", c, m);
                f = c.f;
                f = Flags::sub(c.r[0], c.r[5]).1;
                if f.z {
                    pc = 0x29124c;
                    continue;
                }
                pc = 0x291244;
            }
            0x291244 => {
                c.r[0] = 0x7_u32;
                {
                    let b = c.r[13];
                    c.r[4] = m.r32(b.wrapping_add(0x0));
                    c.r[5] = m.r32(b.wrapping_add(0x4));
                    c.r[13] = b.wrapping_add(0xc);
                    c.f = f;
                    return;
                }
            }
            0x29124c => {
                c.r[0] = 0x0_u32;
                {
                    let b = c.r[13];
                    c.r[4] = m.r32(b.wrapping_add(0x0));
                    c.r[5] = m.r32(b.wrapping_add(0x4));
                    c.r[13] = b.wrapping_add(0xc);
                    c.f = f;
                    return;
                }
            }
            _ => unreachable!("f_002911dc: no block at {pc:#x}"),
        }
    }
}
