//! The voice tree, compiled in.
//!
//! [`FILES`] maps a guest path to its bytes, ready to hand to
//! `Runtime::built_in`. It is generated by `build.rs` from the tree at
//! `$LOQ_LIB`/`$LOQ_DATA`, or from `engine` if those are unset.
//!
//! An empty [`FILES`] means the build found no tree, which is not an error:
//! `loqspeak` then needs `--lib` and `--data`.

include!(concat!(env!("OUT_DIR"), "/voice.rs"));

/// Total size of the built-in tree.
pub fn bytes() -> usize {
    FILES.iter().map(|(_, b)| b.len()).sum()
}

/// Whether this binary carries a voice tree at all.
pub fn present() -> bool {
    !FILES.is_empty()
}
