//! Bake the ARM engine modules into the binary when they are available, so a
//! deployment is one executable plus a voice directory.
//!
//! The modules are looked for in `engine/lib` at the workspace root, or in
//! `$LOQ_ENGINE_LIB`. When neither exists the table is empty and the engine has
//! to be supplied at runtime with `--lib`.

use std::env;
use std::fs;
use std::path::PathBuf;

/// Everything the engine dlopens, plus the driver. Order does not matter.
const WANTED: &[&str] = &[
    "LoqTTS6.so",
    "LoqEnglish6.9.so",
    "loqmsx.so",
    "LoqAudioFile.so",
    "LoqAudioBoard.so",
    "LoqAudioBoardX2.so",
    "tts",
];

fn main() {
    println!("cargo:rerun-if-env-changed=LOQ_ENGINE_LIB");

    let dir = match env::var_os("LOQ_ENGINE_LIB") {
        Some(p) => PathBuf::from(p),
        None => PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(|p| p.parent())
            .and_then(|p| p.parent())
            .map(|p| p.join("engine").join("lib"))
            .unwrap_or_default(),
    };

    let mut entries = Vec::new();
    for name in WANTED {
        let path = dir.join(name);
        println!("cargo:rerun-if-changed={}", path.display());
        if path.is_file() {
            entries.push((name.to_string(), path));
        }
    }

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("embedded.rs");
    let mut src = String::from(
        "// Generated by build.rs. Engine modules baked into the binary.\n\
         pub static MODULES: &[(&str, &[u8])] = &[\n",
    );
    for (name, path) in &entries {
        src.push_str(&format!(
            "    ({:?}, include_bytes!({:?})),\n",
            name,
            path.display().to_string()
        ));
    }
    src.push_str("];\n");
    fs::write(&out, src).expect("writing embedded.rs");

    if entries.is_empty() {
        println!(
            "cargo:warning=no engine modules found in {} - loqdave will need --lib at runtime \
             (run docker/stage-engine.sh, or set LOQ_ENGINE_LIB)",
            dir.display()
        );
    } else {
        let bytes: u64 = entries
            .iter()
            .filter_map(|(_, p)| fs::metadata(p).ok())
            .map(|m| m.len())
            .sum();
        println!(
            "cargo:warning=embedded {} engine modules ({} KiB) from {}",
            entries.len(),
            bytes / 1024,
            dir.display()
        );
    }
}
