//! A native Rust reimplementation of the Loquendo TTS 6 engine.
//!
//! The original is a six-stage pipeline with one uniform module ABI per stage —
//! `Top`, `Les`, `Fon`, `Cat`, `Sig`, `Acu`. The module layout here mirrors
//! that exactly, so a function found in Ghidra has an obvious home:
//!
//! | ARM | here | job |
//! |---|---|---|
//! | `TopRun` `0x6521c` | [`top`] | charset, find-replace tables |
//! | `LesRun` `0x58b10` | [`les`] | tokenise, expand numbers, lexicon |
//! | `FonRun` `0x48c10` | [`fon`] | grapheme-to-phoneme, prosody |
//! | `CatRun` `0x3c21c` | [`cat`] | unit selection |
//! | `SigRun` `0x5af60` | [`sig`] | decode and splice units |
//! | `AcuRun` `0x36690` | [`acu`] | output |
//!
//! # Addresses
//!
//! The doc comments in this crate quote **Ghidra addresses** for `LoqTTS6.so`,
//! because that is where they were read. Ghidra loads at `0x10000` and
//! vaddr == file offset, so:
//!
//! ```text
//! elf_vaddr = ghidra_addr - 0x10000     (also the loqrs module offset)
//! ```
//!
//! `loqmsx.so` addresses are quoted the other way — as module offsets, matching
//! `loqrs`'s `NATIVE_PATCHES`. Add `0x10000` for the listing.
//!
//! Code never relies on that distinction: [`Stage::run_addr`] and
//! [`Stage::ghidra_addr`] each say which they are.
//!
//! **Nothing in this crate runs guest code.** The ARM engine is the oracle, and
//! it lives in `loqng-oracle`, behind a dev-dependency. Building this crate
//! must never pull in the interpreter.
//!
//! Status: scaffolding. See `PLAN.md` for the phase order — the stage modules
//! are empty until their phase starts, and each one is gated on byte-identical
//! output against the oracle.

pub mod stream;

pub mod acu;
pub mod cat;
pub mod les;
pub mod top;

/// Generated tables and cross-check translations. Their own crate so that a
/// runtime edit does not recompile three megabytes of them.
pub use loqng_gen::{fon, sig};
pub mod engine;

/// The runtime translated code executes on. Its own crate so that editing
/// anything here does not recompile 16 MB of generated engine.
pub use loqng_xrt as xrt;

/// The translated engine. Generated by `tools/engxlate.py`.
pub use loqng_eng as eng;

pub use stream::{Phone, PhoneStream, ProsLabel};

/// The stages, in pipeline order.
///
/// `ttsSetModularStructure(h, from, to, scratch)` takes these names as the
/// lowercase strings below and runs that subrange, which is what makes
/// per-stage differential testing possible at all.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Stage {
    Top,
    Les,
    Fon,
    Cat,
    Sig,
    Acu,
}

impl Stage {
    pub const ALL: [Stage; 6] = [
        Stage::Top,
        Stage::Les,
        Stage::Fon,
        Stage::Cat,
        Stage::Sig,
        Stage::Acu,
    ];

    /// The name `ttsSetModularStructure` expects.
    pub fn as_str(self) -> &'static str {
        match self {
            Stage::Top => "top",
            Stage::Les => "les",
            Stage::Fon => "fon",
            Stage::Cat => "cat",
            Stage::Sig => "sig",
            Stage::Acu => "acu",
        }
    }

    pub fn parse(s: &str) -> Option<Stage> {
        Stage::ALL.into_iter().find(|v| v.as_str() == s)
    }

    /// `XxxRun` as an **ELF vaddr**, which is also its `LoqTTS6.so` module
    /// offset — the form a `loqrs` patch table takes. Verified against `nm`.
    pub fn run_addr(self) -> u32 {
        match self {
            Stage::Top => 0x5521c,
            Stage::Les => 0x48b10,
            Stage::Fon => 0x38c10,
            Stage::Cat => 0x2c21c,
            Stage::Sig => 0x4af60,
            Stage::Acu => 0x26690,
        }
    }

    /// `XxxRun` as a **Ghidra address**, for pasting into the listing.
    pub fn ghidra_addr(self) -> u32 {
        self.run_addr() + GHIDRA_BASE
    }
}

/// Ghidra's load address for these modules; vaddr == file offset, so this is
/// the whole of the conversion.
pub const GHIDRA_BASE: u32 = 0x10000;

impl std::fmt::Display for Stage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stage_names_round_trip() {
        for s in Stage::ALL {
            assert_eq!(Stage::parse(s.as_str()), Some(s));
        }
        assert_eq!(Stage::parse("psp"), None);
    }

    /// These came from `nm` on the shipped `LoqTTS6.so`, not from the Ghidra
    /// listing, which is offset by `GHIDRA_BASE`. Getting the two confused
    /// puts a patch 64 KB past the function it was meant for.
    #[test]
    fn run_addresses_are_elf_vaddrs() {
        assert_eq!(Stage::Fon.run_addr(), 0x38c10);
        assert_eq!(Stage::Fon.ghidra_addr(), 0x48c10);
        assert_eq!(Stage::Top.run_addr(), 0x5521c);
        assert_eq!(Stage::Acu.run_addr(), 0x26690);
        for s in Stage::ALL {
            assert_eq!(s.ghidra_addr() - s.run_addr(), GHIDRA_BASE);
        }
    }

    #[test]
    fn stages_are_ordered_front_to_back() {
        assert!(Stage::Top < Stage::Les);
        assert!(Stage::Fon < Stage::Cat);
        assert!(Stage::Sig < Stage::Acu);
    }
}
