//! The US phoneme table -- **generated by `tools/genphon.py`, do not edit**.
//!
//! 87 records of 24 bytes at vaddr `0x7b86c` in `LoqEnglish6.9.so`, reached
//! through the `{PhoneRec *base, int count}` descriptor `ELQGetUSPhonemes`
//! returns. Record 0 is a sentinel with an empty symbol.
//!
//! The symbols are `R_ARM_RELATIVE` pointers and read as zero on disk, so this
//! cannot be lifted with a hex editor; see `notes/eng-fonema-alphabet.md`.

/// One row of the table. `feat` is the articulatory bitfield the narrowing
/// rules test; `narrow` is still undecoded (`notes/eng-data.md` §8 Q2).
#[derive(Clone, Copy, Debug)]
pub struct PhoneRec {
    pub symbol: &'static str,
    pub id: u32,
    pub feat: u32,
    pub narrow: u32,
}

/// `feat` bit 0: set on every vowel and diphthong and on nothing else.
pub const VOWEL: u32 = 0x1;
/// `feat` bit 2: set on every consonant -- the exact complement within the set.
pub const CONS: u32 = 0x4;
/// `feat` bit 9: set only on `OR:` and `` `OR: ``, the two r-coloured vowels.
pub const RCOLOUR: u32 = 0x200;

/// Indexed by the small integer the rules compare against.
pub const PHONES: [PhoneRec; 87] = [
    PhoneRec {
        symbol: "",
        id: 0,
        feat: 0x00000000,
        narrow: 0xffffffff,
    }, // 0
    PhoneRec {
        symbol: "^",
        id: 1,
        feat: 0x00000000,
        narrow: 0xffffffff,
    }, // 1
    PhoneRec {
        symbol: "#",
        id: 2,
        feat: 0x00000000,
        narrow: 0x34c00000,
    }, // 2
    PhoneRec {
        symbol: "@",
        id: 3,
        feat: 0x00000000,
        narrow: 0xeec00000,
    }, // 3
    PhoneRec {
        symbol: "`Aa:",
        id: 2052,
        feat: 0x000810a1,
        narrow: 0x4e401000,
    }, // 4
    PhoneRec {
        symbol: "Aa:",
        id: 1797,
        feat: 0x00081091,
        narrow: 0x4ea20000,
    }, // 5
    PhoneRec {
        symbol: "`Ah",
        id: 2054,
        feat: 0x00021021,
        narrow: 0xb4a00000,
    }, // 6
    PhoneRec {
        symbol: "Ah",
        id: 1799,
        feat: 0x00021011,
        narrow: 0xb4c00000,
    }, // 7
    PhoneRec {
        symbol: "`Ae",
        id: 2056,
        feat: 0x00040421,
        narrow: 0x36a00000,
    }, // 8
    PhoneRec {
        symbol: "Ae",
        id: 1801,
        feat: 0x00040411,
        narrow: 0x36c00000,
    }, // 9
    PhoneRec {
        symbol: "`e",
        id: 2058,
        feat: 0x00020429,
        narrow: 0x62a00000,
    }, // 10
    PhoneRec {
        symbol: "e",
        id: 1803,
        feat: 0x00020419,
        narrow: 0x62c00000,
    }, // 11
    PhoneRec {
        symbol: "`OR:",
        id: 2060,
        feat: 0x00020aa9,
        narrow: 0x66401000,
    }, // 12
    PhoneRec {
        symbol: "OR:",
        id: 1805,
        feat: 0x00020a99,
        narrow: 0x66a20000,
    }, // 13
    PhoneRec {
        symbol: "i",
        id: 1806,
        feat: 0x00002411,
        narrow: 0x10c00000,
    }, // 14
    PhoneRec {
        symbol: "`i:",
        id: 2063,
        feat: 0x000024a1,
        narrow: 0x10401000,
    }, // 15
    PhoneRec {
        symbol: "`I",
        id: 2064,
        feat: 0x00004421,
        narrow: 0x7ca00000,
    }, // 16
    PhoneRec {
        symbol: "I",
        id: 1809,
        feat: 0x00004411,
        narrow: 0x7cc00000,
    }, // 17
    PhoneRec {
        symbol: "`Oa:",
        id: 2066,
        feat: 0x001210a1,
        narrow: 0x54401000,
    }, // 18
    PhoneRec {
        symbol: "Oa:",
        id: 1811,
        feat: 0x00121091,
        narrow: 0x54a20000,
    }, // 19
    PhoneRec {
        symbol: "`u:",
        id: 2068,
        feat: 0x001030a1,
        narrow: 0x28401000,
    }, // 20
    PhoneRec {
        symbol: "u",
        id: 1813,
        feat: 0x00103011,
        narrow: 0x28c00000,
    }, // 21
    PhoneRec {
        symbol: "`U",
        id: 2070,
        feat: 0x00105021,
        narrow: 0xb0a00000,
    }, // 22
    PhoneRec {
        symbol: "U",
        id: 1815,
        feat: 0x00105011,
        narrow: 0xb0c00000,
    }, // 23
    PhoneRec {
        symbol: "HEh",
        id: 1560,
        feat: 0x00010851,
        narrow: 0x5ec00000,
    }, // 24
    PhoneRec {
        symbol: "`HAI",
        id: 2585,
        feat: 0x022808a3,
        narrow: 0x016f8000,
    }, // 25
    PhoneRec {
        symbol: "HAI",
        id: 2330,
        feat: 0x02280893,
        narrow: 0x01be0000,
    }, // 26
    PhoneRec {
        symbol: "`HAU",
        id: 2587,
        feat: 0x828808a3,
        narrow: 0x01760000,
    }, // 27
    PhoneRec {
        symbol: "HAU",
        id: 2332,
        feat: 0x82880893,
        narrow: 0x01d80000,
    }, // 28
    PhoneRec {
        symbol: "`HEI",
        id: 2589,
        feat: 0x022204a3,
        narrow: 0x096f8000,
    }, // 29
    PhoneRec {
        symbol: "HEI",
        id: 2334,
        feat: 0x02220493,
        narrow: 0x09be0000,
    }, // 30
    PhoneRec {
        symbol: "`HOI",
        id: 2591,
        feat: 0x023090a3,
        narrow: 0x556f8000,
    }, // 31
    PhoneRec {
        symbol: "HOI",
        id: 2336,
        feat: 0x02309093,
        narrow: 0x55be0000,
    }, // 32
    PhoneRec {
        symbol: "`HOU",
        id: 2593,
        feat: 0x829090a3,
        narrow: 0x1d760000,
    }, // 33
    PhoneRec {
        symbol: "HOU",
        id: 2338,
        feat: 0x82909093,
        narrow: 0x1dd80000,
    }, // 34
    PhoneRec {
        symbol: "w",
        id: 1571,
        feat: 0x01102404,
        narrow: 0x2cc00000,
    }, // 35
    PhoneRec {
        symbol: "Hw",
        id: 804,
        feat: 0x8110240c,
        narrow: 0x2cc00000,
    }, // 36
    PhoneRec {
        symbol: "j",
        id: 1573,
        feat: 0x01080404,
        narrow: 0x12c00000,
    }, // 37
    PhoneRec {
        symbol: "Hj",
        id: 806,
        feat: 0x8108040c,
        narrow: 0x12c80000,
    }, // 38
    PhoneRec {
        symbol: "Hr",
        id: 1575,
        feat: 0x01010404,
        narrow: 0x98c00000,
    }, // 39
    PhoneRec {
        symbol: "HR",
        id: 1576,
        feat: 0x09010404,
        narrow: 0x98b60000,
    }, // 40
    PhoneRec {
        symbol: "Hg",
        id: 809,
        feat: 0x01800014,
        narrow: 0xc4ac0000,
    }, // 41
    PhoneRec {
        symbol: "Hk",
        id: 810,
        feat: 0x00800014,
        narrow: 0xc4c00000,
    }, // 42
    PhoneRec {
        symbol: "p",
        id: 555,
        feat: 0x0200201c,
        narrow: 0x1ec00000,
    }, // 43
    PhoneRec {
        symbol: "ph",
        id: 556,
        feat: 0x12002014,
        narrow: 0x1ea40000,
    }, // 44
    PhoneRec {
        symbol: "Hup",
        id: 557,
        feat: 0x22002014,
        narrow: 0x1ece0000,
    }, // 45
    PhoneRec {
        symbol: "t",
        id: 558,
        feat: 0x0201001c,
        narrow: 0x26c00000,
    }, // 46
    PhoneRec {
        symbol: "th",
        id: 559,
        feat: 0x12010014,
        narrow: 0x26a40000,
    }, // 47
    PhoneRec {
        symbol: "Hut",
        id: 560,
        feat: 0x22010014,
        narrow: 0x26ce0000,
    }, // 48
    PhoneRec {
        symbol: "k",
        id: 561,
        feat: 0x0210001c,
        narrow: 0x14c00000,
    }, // 49
    PhoneRec {
        symbol: "kh",
        id: 562,
        feat: 0x12100014,
        narrow: 0x14a40000,
    }, // 50
    PhoneRec {
        symbol: "Huk",
        id: 307,
        feat: 0x22100014,
        narrow: 0x14ce0000,
    }, // 51
    PhoneRec {
        symbol: "HTh",
        id: 820,
        feat: 0x0301001c,
        narrow: 0x26ac0000,
    }, // 52
    PhoneRec {
        symbol: "b",
        id: 821,
        feat: 0x03002014,
        narrow: 0x02c00000,
    }, // 53
    PhoneRec {
        symbol: "Hub",
        id: 822,
        feat: 0x23002014,
        narrow: 0x02ce0000,
    }, // 54
    PhoneRec {
        symbol: "HB",
        id: 567,
        feat: 0x4200201c,
        narrow: 0x02ab0000,
    }, // 55
    PhoneRec {
        symbol: "d",
        id: 824,
        feat: 0x03010014,
        narrow: 0x06c00000,
    }, // 56
    PhoneRec {
        symbol: "Hud",
        id: 825,
        feat: 0x23010014,
        narrow: 0x06ce0000,
    }, // 57
    PhoneRec {
        symbol: "HD",
        id: 570,
        feat: 0x4201001c,
        narrow: 0x06ab0000,
    }, // 58
    PhoneRec {
        symbol: "g",
        id: 827,
        feat: 0x03100014,
        narrow: 0x0cc00000,
    }, // 59
    PhoneRec {
        symbol: "Hug",
        id: 828,
        feat: 0x23100014,
        narrow: 0x0cce0000,
    }, // 60
    PhoneRec {
        symbol: "HG",
        id: 573,
        feat: 0x4210001c,
        narrow: 0x0cca0000,
    }, // 61
    PhoneRec {
        symbol: "Ts",
        id: 574,
        feat: 0x02011004,
        narrow: 0xe2c00000,
    }, // 62
    PhoneRec {
        symbol: "T$",
        id: 575,
        feat: 0x02021004,
        narrow: 0xe4c00000,
    }, // 63
    PhoneRec {
        symbol: "Dz",
        id: 832,
        feat: 0x0301100c,
        narrow: 0xdcc00000,
    }, // 64
    PhoneRec {
        symbol: "Dg",
        id: 833,
        feat: 0x03021004,
        narrow: 0xdec00000,
    }, // 65
    PhoneRec {
        symbol: "f",
        id: 578,
        feat: 0x02004104,
        narrow: 0x0ac00000,
    }, // 66
    PhoneRec {
        symbol: "v",
        id: 835,
        feat: 0x03004104,
        narrow: 0x2ac00000,
    }, // 67
    PhoneRec {
        symbol: "Hv",
        id: 580,
        feat: 0x4200410c,
        narrow: 0x2aab0000,
    }, // 68
    PhoneRec {
        symbol: "s",
        id: 581,
        feat: 0x00010104,
        narrow: 0x24c00000,
    }, // 69
    PhoneRec {
        symbol: "z",
        id: 838,
        feat: 0x01010104,
        narrow: 0x32c00000,
    }, // 70
    PhoneRec {
        symbol: "Hz",
        id: 583,
        feat: 0x4001010c,
        narrow: 0x32ab0000,
    }, // 71
    PhoneRec {
        symbol: "$",
        id: 584,
        feat: 0x00020104,
        narrow: 0xa8c00000,
    }, // 72
    PhoneRec {
        symbol: "Zg",
        id: 841,
        feat: 0x01020104,
        narrow: 0xc0c00000,
    }, // 73
    PhoneRec {
        symbol: "Th",
        id: 586,
        feat: 0x02008104,
        narrow: 0xeac00000,
    }, // 74
    PhoneRec {
        symbol: "Dh",
        id: 843,
        feat: 0x03008104,
        narrow: 0x3ac00000,
    }, // 75
    PhoneRec {
        symbol: "HDh",
        id: 588,
        feat: 0x4200810c,
        narrow: 0x3aab0000,
    }, // 76
    PhoneRec {
        symbol: "h",
        id: 589,
        feat: 0x00800104,
        narrow: 0x0ec00000,
    }, // 77
    PhoneRec {
        symbol: "Hh",
        id: 846,
        feat: 0x0180010c,
        narrow: 0x76c00000,
    }, // 78
    PhoneRec {
        symbol: "m",
        id: 1359,
        feat: 0x01002024,
        narrow: 0x18c00000,
    }, // 79
    PhoneRec {
        symbol: "n",
        id: 1360,
        feat: 0x01010024,
        narrow: 0x1ac00000,
    }, // 80
    PhoneRec {
        symbol: "Hn",
        id: 1361,
        feat: 0x09010024,
        narrow: 0x1ab60000,
    }, // 81
    PhoneRec {
        symbol: "N",
        id: 1362,
        feat: 0x01100024,
        narrow: 0x40c00000,
    }, // 82
    PhoneRec {
        symbol: "l",
        id: 1875,
        feat: 0x01010804,
        narrow: 0x16c00000,
    }, // 83
    PhoneRec {
        symbol: "Hl",
        id: 1876,
        feat: 0x09010804,
        narrow: 0x16b60000,
    }, // 84
    PhoneRec {
        symbol: "`E",
        id: 2133,
        feat: 0x00020421,
        narrow: 0x62a00000,
    }, // 85
    PhoneRec {
        symbol: "E",
        id: 1878,
        feat: 0x00020411,
        narrow: 0x62c00000,
    }, // 86
];

/// Look a symbol up by name; linear, and only for tests and dumps.
pub fn code_of(symbol: &str) -> Option<u8> {
    PHONES
        .iter()
        .position(|p| p.symbol == symbol)
        .map(|i| i as u8)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_alphabet_is_the_one_the_corpus_uses() {
        // Every symbol in the `stage-fon` dump for capture 0000.
        for s in [
            "th", "`E", "s", "I", "N", "w", "`Ah", "n", "`u:", "Th", "Hr", "`i:", "@",
        ] {
            assert!(code_of(s).is_some(), "{s} is not in the table");
        }
    }

    #[test]
    fn vowel_and_consonant_partition_the_alphabet() {
        for (i, p) in PHONES.iter().enumerate().skip(1) {
            if p.symbol.is_empty() || matches!(p.symbol, "^" | "#" | "@") {
                continue;
            }
            let v = p.feat & VOWEL != 0;
            let c = p.feat & CONS != 0;
            assert!(v != c, "{} (code {i}) is both or neither", p.symbol);
        }
    }
}
